Allow larger files to be uploaded via the API
Currently, any images added to events larger than 1MB will result in an
error: `client intended to send too large body`. This is because the
default [client_max_body_size] is 1 MB. This commit increases that limit
to 20 MB so that larger images can be uploaded.

[client_max_body_size]: https://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size